"""initial

Revision ID: ecb680872446
Revises: f1f78e7a4900
Create Date: 2025-11-26 23:14:06.076642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb680872446'
down_revision: Union[str, Sequence[str], None] = 'f1f78e7a4900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('colore', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_category_id'), 'tb_category', ['id'], unique=False)
    op.create_table('tb_sub_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=5), nullable=True),
    sa.Column('colore', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tb_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_sub_category_id'), 'tb_sub_category', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_sub_category_id'), table_name='tb_sub_category')
    op.drop_table('tb_sub_category')
    op.drop_index(op.f('ix_tb_category_id'), table_name='tb_category')
    op.drop_table('tb_category')
    # ### end Alembic commands ###
